"""The MaleCNS v1.0 source lock (`data/malecns_v1.lock.json`): which official files Fly Golf
compiles, their sizes and digests, and the counts Fly Golf's compiler produces from them.

    fly-golf-data lock            regenerate the lock from the official release
    fly-golf-data verify-source   check local files against the lock (and --remote: the lock
                                  against the official bucket's own object metadata)

The lock is generated by Fly Golf directly against the official release: each file's size and
MD5 are compared with the metadata the release bucket publishes for that object (Google Cloud
Storage `x-goog-hash`, `Content-Length`), then SHA-256 is computed locally. Nothing is copied
from another project's lock.
"""

from __future__ import annotations

import base64
import hashlib
import re
import time
import urllib.request
from collections.abc import Callable
from pathlib import Path

LOCK_SCHEMA = "fly-golf-source-lock-v2"
RELEASE_PAGE = "https://male-cns.janelia.org/download/"
OFFICIAL_BASE = "https://storage.googleapis.com/flyem-male-cns/v1.0/connectome-data/flat-connectome"
# local name -> official file name (the flat connectome at synapse confidence >= 0.5)
SOURCE_FILES = {
    "annotations.feather": "body-annotations-male-cns-v1.0-minconf-0.5.feather",
    "neurotransmitters.feather": "body-neurotransmitters-male-cns-v1.0.feather",
    "edges.feather": "connectome-weights-male-cns-v1.0-minconf-0.5.feather",
}
RELEASE = {
    "dataset": "malecns_v1",
    "release": "MaleCNS v1.0",
    "sex": "male",
    "coverage": "brain_and_ventral_nerve_cord",
    "license": "CC BY 4.0",
    "release_page": RELEASE_PAGE,
    "paper": "https://doi.org/10.1016/j.cell.2026.08.015",
}
_HEX64 = re.compile(r"^[0-9a-f]{64}$")
_HEX32 = re.compile(r"^[0-9a-f]{32}$")


class LockError(ValueError):
    """The lock file is malformed, or a source file does not match it."""


def validate_lock(lock: dict) -> dict:
    """Raise LockError unless `lock` has everything acquisition and compilation rely on."""
    if not isinstance(lock, dict):
        raise LockError("lock must be a JSON object")
    for key in ("dataset", "release", "license", "files"):
        if key not in lock:
            raise LockError(f"lock has no {key!r}")
    files = lock["files"]
    if not isinstance(files, dict) or set(files) != set(SOURCE_FILES):
        raise LockError(f"lock must list exactly {sorted(SOURCE_FILES)}")
    for name, info in files.items():
        if not isinstance(info, dict):
            raise LockError(f"{name}: entry must be an object")
        if not str(info.get("url", "")).startswith("https://"):
            raise LockError(f"{name}: url must be https")
        if not isinstance(info.get("bytes"), int) or info["bytes"] <= 0:
            raise LockError(f"{name}: bytes must be a positive integer")
        if not _HEX64.match(str(info.get("sha256", ""))):
            raise LockError(f"{name}: sha256 must be 64 lowercase hex digits")
        if "md5" in info and not _HEX32.match(str(info["md5"])):
            raise LockError(f"{name}: md5 must be 32 lowercase hex digits")
    return lock


def file_digests(path: Path) -> dict:
    """Size, SHA-256 and MD5 of a file, in one pass."""
    sha, md5 = hashlib.sha256(), hashlib.md5()
    size = 0
    with Path(path).open("rb") as fh:
        while chunk := fh.read(8 * 1024 * 1024):
            sha.update(chunk)
            md5.update(chunk)
            size += len(chunk)
    return {"bytes": size, "sha256": sha.hexdigest(), "md5": md5.hexdigest()}


def remote_metadata(url: str, timeout: float = 30.0) -> dict:
    """What the official bucket says about one object (HEAD request; nothing is downloaded)."""
    req = urllib.request.Request(url, method="HEAD")
    with urllib.request.urlopen(req, timeout=timeout) as resp:
        headers = resp.headers
        hashes = {}
        for value in headers.get_all("x-goog-hash") or []:
            for part in value.split(","):
                algo, _, b64 = part.strip().partition("=")
                hashes[algo] = base64.b64decode(b64).hex()
        return {
            "bytes": int(headers["Content-Length"]),
            "md5": hashes.get("md5"),
            "crc32c": hashes.get("crc32c"),
            "generation": headers.get("x-goog-generation"),
            "last_modified": headers.get("Last-Modified"),
        }


def verify_local(lock: dict, raw_dir: Path) -> dict[str, str]:
    """Per file: ok | missing | wrong_size | sha256_mismatch (hashes every present file)."""
    validate_lock(lock)
    out = {}
    for name, info in lock["files"].items():
        path = Path(raw_dir) / name
        if not path.exists():
            out[name] = "missing"
        elif path.stat().st_size != info["bytes"]:
            out[name] = "wrong_size"
        elif file_digests(path)["sha256"] != info["sha256"]:
            out[name] = "sha256_mismatch"
        else:
            out[name] = "ok"
    return out


def verify_remote(lock: dict, fetch: Callable[[str], dict] = remote_metadata) -> dict[str, str]:
    """Per file: ok | size_mismatch | md5_mismatch | no_md5 (the lock against the official bucket)."""
    validate_lock(lock)
    out = {}
    for name, info in lock["files"].items():
        meta = fetch(info["url"])
        if meta["bytes"] != info["bytes"]:
            out[name] = "size_mismatch"
        elif not meta.get("md5") or "md5" not in info:
            out[name] = "no_md5"
        elif meta["md5"] != info["md5"]:
            out[name] = "md5_mismatch"
        else:
            out[name] = "ok"
    return out


def build_lock(
    raw_dir: Path,
    expected_compiled: dict | None,
    fetch: Callable[[str], dict] = remote_metadata,
) -> dict:
    """A lock for the files in `raw_dir`, each checked against the official object metadata.

    Raises LockError if a local file is not byte-for-byte the official object (size and MD5
    must equal what the release bucket reports)."""
    files = {}
    for name, official in SOURCE_FILES.items():
        url = f"{OFFICIAL_BASE}/{official}"
        path = Path(raw_dir) / name
        if not path.exists():
            raise LockError(f"{path} is missing; download it from {url}")
        meta = fetch(url)
        local = file_digests(path)
        if local["bytes"] != meta["bytes"]:
            raise LockError(f"{name}: {local['bytes']} bytes locally, {meta['bytes']} in the official release")
        if not meta.get("md5"):
            raise LockError(f"{name}: the release server published no MD5 to verify against")
        if local["md5"] != meta["md5"]:
            raise LockError(f"{name}: MD5 differs from the official object; re-download it")
        files[name] = {
            "url": url,
            "bytes": local["bytes"],
            "sha256": local["sha256"],
            "md5": local["md5"],
            "gcs_generation": meta.get("generation"),
            "last_modified": meta.get("last_modified"),
        }
    lock = {
        "schema": LOCK_SCHEMA,
        **RELEASE,
        "generated_by": "fly-golf-data lock",
        "generated_utc": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "verification": (
            "Each file's size and MD5 were checked against the object metadata published by the "
            "official MaleCNS v1.0 bucket (Content-Length, x-goog-hash); SHA-256 computed by Fly Golf."
        ),
        "expected_compiled": expected_compiled or {},
        "files": files,
    }
    return validate_lock(lock)
